// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA1rykMNbcn1DVKsVyrJgctFKbLYFcDqE',
    appId: '1:1033094175415:web:41eefb6a47d1b98d898b32',
    messagingSenderId: '1033094175415',
    projectId: 'in-class-activity-14',
    authDomain: 'in-class-activity-14.firebaseapp.com',
    storageBucket: 'in-class-activity-14.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ZQBr2AMniby1w7lAklZaRKM41-WLu84',
    appId: '1:1033094175415:android:a8dd8e1532b0fbbb898b32',
    messagingSenderId: '1033094175415',
    projectId: 'in-class-activity-14',
    storageBucket: 'in-class-activity-14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVK4rz-tQXf1UqRl_s2nRMCkdHjXQj9-o',
    appId: '1:1033094175415:ios:c0feb4d1007bc9a4898b32',
    messagingSenderId: '1033094175415',
    projectId: 'in-class-activity-14',
    storageBucket: 'in-class-activity-14.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVK4rz-tQXf1UqRl_s2nRMCkdHjXQj9-o',
    appId: '1:1033094175415:ios:c0feb4d1007bc9a4898b32',
    messagingSenderId: '1033094175415',
    projectId: 'in-class-activity-14',
    storageBucket: 'in-class-activity-14.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA1rykMNbcn1DVKsVyrJgctFKbLYFcDqE',
    appId: '1:1033094175415:web:ef0937083a63916d898b32',
    messagingSenderId: '1033094175415',
    projectId: 'in-class-activity-14',
    authDomain: 'in-class-activity-14.firebaseapp.com',
    storageBucket: 'in-class-activity-14.firebasestorage.app',
  );
}
